version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - unparam
    - prealloc
  settings:
    misspell:
      locale: US

issues:
  max-issues-per-linter: 50
  max-same-issues: 10
